version: "3.8"
services:
    authentication_service_postgres_main_database:
        image: postgres:13.3
        container_name: authentication_service_postgres_dev
        hostname: postgres
        environment:
            - POSTGRES_DB=AuthenticationServiceDatabase
            - POSTGRES_USER=AuthenticationService
            - POSTGRES_PASSWORD=auth785Service368Password
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./postgres/2. Init Database:/docker-entrypoint-initdb.d
            - ./postgres:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        networks:
            - authentication_service_local

    authentication_service_mongo_main_database:
        image: mongo
        container_name: authentication_service_mongo_dev
        ports:
            - "27018:27017"
        volumes:
            - ./mongo:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=AuthenticationServiceRoot
            - MONGO_INITDB_ROOT_PASSWORD=auth785Service368Password
        networks: 
            - authentication_service_local

    authentication_service_mongo_express:
        image: mongo-express
        container_name: authentication_service_mongo_express_dev
        ports:
            - "8082:8081"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=AuthenticationServiceRoot
            - ME_CONFIG_MONGODB_ADMINPASSWORD=auth785Service368Password
            - ME_CONFIG_MONGODB_SERVER=authentication_service_mongo_main_database
        networks: 
            - authentication_service_local

    authentication_service_redis_token_blacklist:
        image: redis:alpine
        container_name: authentication_service_redis_dev
        hostname: redis
        command: redis-server --requirepass "redis578passw"
        ports: 
            - "6380:6379"
        volumes: 
            - ./redis:/var/lib/redis
        environment: 
            - REDIS_REPLICATION_MODE=master
        networks: 
            - authentication_service_local
    
    authentication_service_seq_server:
        image: datalust/seq:latest
        container_name: authentication_service_seq_server_dev
        hostname: seqserver
        ports:
            - "5341:80"
        volumes:
            - ./seqserver:/data
        environment: 
            - ACCEPT_EULA=Y
        networks: 
            - authentication_service_local

networks:
    authentication_service_local:
